# Generated by Django 6.1 on 2026-08-24 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
        ('residents', '0009_resident_bed_type_room_beds_lower_room_beds_upper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('photo_url', models.URLField(blank=True, verbose_name='Посилання на фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Посилання на відео')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('position_title', models.CharField(max_length=150, verbose_name='Посада/роль')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('photo_url', models.URLField(blank=True, verbose_name='Посилання на фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показу')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.center', verbose_name='Центр')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
