# Generated by Django 6.1 on 2026-08-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название центра')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Директор')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер/название комнаты')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.center', verbose_name='Центр')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('status', models.CharField(choices=[('residing', 'Проживает'), ('departed', 'Убыл'), ('hospitalized', 'В больнице'), ('absent', 'Временно отсутствует')], default='residing', max_length=20, verbose_name='Статус')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата убытия')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('extra_attributes', models.JSONField(blank=True, default=dict, help_text='Произвольные данные (заболевания, суды, льготы и т.д.)', verbose_name='Доп. атрибуты')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='residents.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Подопечный',
                'verbose_name_plural': 'Подопечные',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
