# Generated by Django 6.1 on 2026-08-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Підопічний', 'verbose_name_plural': 'Підопічні'},
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва центру'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прибуття'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вибуття'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Довільні дані (захворювання, суди, пільги тощо)', verbose_name='Додаткові атрибути'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловіча'), ('F', 'Жіноча')], max_length=1, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='residents.room', verbose_name='Кімната'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('residing', 'Проживає'), ('departed', 'Вибув'), ('hospitalized', 'У лікарні'), ('absent', 'Тимчасово відсутній')], default='residing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Місткість'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Номер/назва кімнати'),
        ),
    ]
