# Generated by Django 6.1 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_options_alter_center_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва ролі')),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='roles',
            field=models.ManyToManyField(blank=True, to='residents.role', verbose_name='Ролі'),
        ),
    ]
