# Generated by Django 6.1 on 2026-08-23 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва посади')),
                ('level', models.CharField(choices=[('owner', 'Власник'), ('branch_director', 'Директор філії'), ('center_director', 'Директор центру'), ('admin_1', 'Адміністратор 1'), ('admin_2', 'Адміністратор 2'), ('admin_3', 'Адміністратор 3')], max_length=20, verbose_name='Рівень доступу')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='Обліковий запис'),
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата призначення')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.position', verbose_name='Посада')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident', verbose_name='Резидент')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата дії')),
                ('description', models.TextField(verbose_name='Опис дії')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='residents.positionassignment', verbose_name='Призначення')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
