# Generated by Django 6.1 on 2026-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_remove_room_user_account_resident_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
    ]
