# Generated by Django 6.1 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_actionlog_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='avatar',
        ),
        migrations.AddField(
            model_name='resident',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
    ]
