# Generated by Django 6.1 on 2026-08-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_remove_actionlog_avatar_resident_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('upper', 'Верхнє'), ('lower', 'Нижнє')], max_length=10, null=True, verbose_name='Місце'),
        ),
        migrations.AddField(
            model_name='room',
            name='beds_lower',
            field=models.PositiveIntegerField(default=0, verbose_name='Нижніх місць'),
        ),
        migrations.AddField(
            model_name='room',
            name='beds_upper',
            field=models.PositiveIntegerField(default=0, verbose_name='Верхніх місць'),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки (інвентар тощо)'),
        ),
    ]
