# Generated by Django 6.1 on 2026-08-24 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_resident_bed_type_room_beds_lower_room_beds_upper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_role_requests', to=settings.AUTH_USER_MODEL, verbose_name='Хто затвердив')),
                ('current_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_role_requests', to='residents.role', verbose_name='Поточна роль')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_role_requests', to=settings.AUTH_USER_MODEL, verbose_name='Хто запропонував')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to='residents.resident', verbose_name='Підопічний')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_role_requests', to='residents.role', verbose_name='Цільова роль')),
            ],
            options={
                'verbose_name': 'Заявка на зміну ролі',
                'verbose_name_plural': 'Заявки на зміну ролей',
            },
        ),
    ]
